services:
  db:
    image: postgres:16-alpine
    container_name: bundestagstracker_db
    env_file: .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - bt-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  app:
    build: .
    container_name: bundestagstracker_app
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: always
    networks:
      - bt-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx512m -Xms256m"

volumes:
  postgres_data:

networks:
  bt-network:
    driver: bridge
